CREATE TABLE IF NOT EXISTS products(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, data LONGTEXT NOT NULL CHECK(JSON_VALID(data))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS customers(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, data LONGTEXT NOT NULL CHECK(JSON_VALID(data))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS vendors(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, data LONGTEXT NOT NULL CHECK(JSON_VALID(data))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS documents(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, kind VARCHAR(20) NOT NULL, date VARCHAR(10) NOT NULL, data LONGTEXT NOT NULL CHECK(JSON_VALID(data)), INDEX document_kind_date(kind,date)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS movements(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, productId INT UNSIGNED NOT NULL, date VARCHAR(10) NOT NULL, quantity DOUBLE NOT NULL, reason VARCHAR(255) NOT NULL, INDEX movement_date(date), FOREIGN KEY(productId) REFERENCES products(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(60) NOT NULL, permissions LONGTEXT NOT NULL CHECK(JSON_VALID(permissions))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sessions(token VARCHAR(64) PRIMARY KEY, userId INT UNSIGNED NOT NULL, expires BIGINT NOT NULL, duration BIGINT NOT NULL DEFAULT 86400000, INDEX session_expiry(expires), FOREIGN KEY(userId) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, date VARCHAR(40), actor VARCHAR(120), action VARCHAR(255), details TEXT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS settings(id INT UNSIGNED PRIMARY KEY, data LONGTEXT NOT NULL CHECK(JSON_VALID(data)), CHECK(id=1)) ENGINE=InnoDB;
