import express from 'express';
import { createServer as createHttpServer } from 'node:http';
import { publicOrigins, validOrigin } from './origins.js';
import { randomBytes } from 'node:crypto';
import { openDB,seed,rows,put,hashPassword,verifyPassword,createDocument } from './db.js';
const db=openDB(process.env.DB_PATH||'data/tradeflow.sqlite');seed(db);
const configuredOrigins=publicOrigins();
function safeOrigin(value){try{return new URL(value).origin;}catch{return '(invalid origin)';}}
const app=express();const httpServer=createHttpServer(app);app.disable('x-powered-by');app.use(express.json({limit:'3mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');if(req.method!=='GET'&&!validOrigin(req,configuredOrigins))return res.status(403).json({error:`Invalid request origin. Received: ${safeOrigin(req.headers.origin)}. Expected: ${configuredOrigins.join(', ')||`${req.protocol}://${req.get('host')}`}.`,code:'ORIGIN_MISMATCH'});next();});
app.get('/api/health',(req,res)=>{db.prepare('SELECT 1').get();res.json({status:'ok',version:'codespaces-2',publicOrigins:configuredOrigins});});
const attempts=new Map();
app.post('/api/login',(req,res)=>{const key=req.ip;const a=attempts.get(key)||{n:0,time:Date.now()};if(Date.now()-a.time>900000){a.n=0;a.time=Date.now();}if(a.n>=20)return res.status(429).json({error:'Too many attempts. Try again in 15 minutes.'});const user=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase());if(!user||!verifyPassword(String(req.body.password||''),user.password)){a.n++;attempts.set(key,a);return res.status(401).json({error:'Email or password is incorrect'});}attempts.delete(key);const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(token,user.id,Date.now()+86400000);res.cookie('session',token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='true',maxAge:86400000});res.json({ok:true});});
app.use('/api',(req,res,next)=>{const token=req.headers.cookie?.split(';').map(c=>c.trim()).find(c=>c.startsWith('session='))?.slice(8);const session=db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(token||'',Date.now());if(!session)return res.status(401).json({error:'Please sign in'});req.user=db.prepare('SELECT * FROM users WHERE id=?').get(session.userId);req.permissions=JSON.parse(req.user.permissions);req.token=token;next();});
const permit=(module,action)=>(req,res,next)=>req.permissions[module]?.includes(action)?next():res.status(403).json({error:'You do not have permission for this action'});
const audit=(req,action,details)=>db.prepare('INSERT INTO audit(date,actor,action,details) VALUES(?,?,?,?)').run(new Date().toISOString(),req.user.name,action,details);
app.get('/api/state',(req,res)=>{const allowed=m=>req.permissions[m]?.includes('view');const docs=rows(db,'documents').filter(d=>allowed(['payments','cash'].includes(d.kind)?'finance':d.kind==='adjustments'?'inventory':d.kind));res.json({user:{id:req.user.id,name:req.user.name,email:req.user.email,role:req.user.role,permissions:req.permissions},products:allowed('products')||allowed('inventory')||allowed('sales')||allowed('purchases')?rows(db,'products'):[],customers:allowed('customers')||allowed('sales')||allowed('finance')?rows(db,'customers'):[],vendors:allowed('vendors')||allowed('purchases')||allowed('finance')?rows(db,'vendors'):[],documents:docs,movements:allowed('inventory')?db.prepare('SELECT * FROM movements ORDER BY id DESC').all():[],settings:JSON.parse(db.prepare('SELECT data FROM settings').get().data),users:allowed('admin')?db.prepare('SELECT id,name,email,role,permissions FROM users').all().map(u=>({...u,permissions:JSON.parse(u.permissions)})):[],audit:allowed('admin')?db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 200').all():[]});});
app.post('/api/password',(req,res,next)=>{try{if(!verifyPassword(String(req.body.current||''),req.user.password))throw Error('Current password is incorrect');if(typeof req.body.password!=='string'||req.body.password.length<10)throw Error('Use at least 10 characters');db.prepare('UPDATE users SET password=? WHERE id=?').run(hashPassword(req.body.password),req.user.id);db.prepare('DELETE FROM sessions WHERE userId=? AND token<>?').run(req.user.id,req.token);audit(req,'Changed password','Other sessions revoked');res.json({ok:true});}catch(e){next(e);}});
app.post('/api/logout',(req,res)=>{db.prepare('DELETE FROM sessions WHERE token=?').run(req.token);res.clearCookie('session');res.json({ok:true});});
for(const table of ['products','customers','vendors']){
 app.post(`/api/${table}`,permit(table,'add'),(req,res,next)=>{try{const d={...req.body};if(!d.name?.trim())throw Error('Name is required');if(table==='products'){if(!d.sku?.trim())throw Error('SKU is required');if(rows(db,table).some(p=>p.sku.toLowerCase()===d.sku.toLowerCase()))throw Error('SKU already exists');for(const k of ['purchasePrice','sellingPrice','minStock','openingStock']){d[k]=Number(d[k]||0);if(!Number.isFinite(d[k])||d[k]<0)throw Error('Prices and stock must be nonnegative');}d.stock=d.openingStock;}else{d.openingBalance=Number(d.openingBalance||0);if(!Number.isFinite(d.openingBalance)||d.openingBalance<0)throw Error('Invalid opening balance');d.balance=d.openingBalance;}const id=put(db,table,d);audit(req,`Created ${table}`,d.name);res.json({id});}catch(e){next(e);}});
 app.put(`/api/${table}/:id`,permit(table,'edit'),(req,res,next)=>{try{const old=rows(db,table).find(r=>r.id===Number(req.params.id));if(!old)return res.status(404).json({error:'Record not found'});const d={...old,...req.body,id:old.id,stock:old.stock,balance:old.balance,openingStock:old.openingStock,openingBalance:old.openingBalance};if(!d.name?.trim())throw Error('Name is required');if(table==='products'){if(!d.sku?.trim()||rows(db,table).some(p=>p.id!==old.id&&p.sku===d.sku))throw Error('SKU must be unique');for(const k of ['purchasePrice','sellingPrice','minStock']){d[k]=Number(d[k]);if(!Number.isFinite(d[k])||d[k]<0)throw Error('Invalid price or stock level');}}put(db,table,d,old.id);audit(req,`Updated ${table}`,d.name);res.json({ok:true});}catch(e){next(e);}});
 app.delete(`/api/${table}/:id`,permit(table,'delete'),(req,res,next)=>{try{const id=Number(req.params.id);const linked=rows(db,'documents').some(d=>table==='products'?d.items?.some(i=>Number(i.productId)===id)||Number(d.productId)===id:Number(d.partyId)===id&&(table==='customers'?d.kind==='sales'||d.direction==='received':d.kind==='purchases'||d.direction==='paid'));if(linked)throw Error('This record has transactions. Keep it for ledger accuracy.');db.prepare(`DELETE FROM ${table} WHERE id=?`).run(id);audit(req,`Deleted ${table}`,String(id));res.json({ok:true});}catch(e){next(e);}});
}
app.post('/api/documents/:kind',(req,res,next)=>{try{const kind=req.params.kind,module=['payments','cash'].includes(kind)?'finance':kind==='adjustments'?'inventory':kind;if(!req.permissions[module]?.includes('add'))return res.status(403).json({error:'Permission denied'});const doc=createDocument(db,kind,req.body);audit(req,`Created ${kind}`,doc.number);res.json(doc);}catch(e){next(e);}});
app.put('/api/settings',permit('admin','edit'),(req,res)=>{if(!req.body.company?.trim())return res.status(400).json({error:'Company name is required'});put(db,'settings',req.body,1);audit(req,'Updated company settings',req.body.company);res.json({ok:true});});
app.post('/api/users',permit('admin','add'),(req,res,next)=>{try{const {name,email,password,role,permissions}=req.body;if(!name||!email?.includes('@')||password?.length<10)throw Error('Name, valid email and password of at least 10 characters required');db.prepare('INSERT INTO users(name,email,password,role,permissions) VALUES(?,?,?,?,?)').run(name,email.toLowerCase(),hashPassword(password),role,JSON.stringify(permissions));audit(req,'Created user',email);res.json({ok:true});}catch(e){next(e);}});
app.put('/api/users/:id',permit('admin','edit'),(req,res,next)=>{try{if(Number(req.params.id)===req.user.id)throw Error('You cannot change your own role');const {name,role,permissions}=req.body;if(!name||!role)throw Error('Name and role required');db.prepare('UPDATE users SET name=?,role=?,permissions=? WHERE id=?').run(name,role,JSON.stringify(permissions),Number(req.params.id));db.prepare('DELETE FROM sessions WHERE userId=?').run(Number(req.params.id));audit(req,'Updated user',name);res.json({ok:true});}catch(e){next(e);}});
app.delete('/api/users/:id',permit('admin','delete'),(req,res,next)=>{try{if(Number(req.params.id)===req.user.id)throw Error('You cannot delete yourself');db.prepare('DELETE FROM sessions WHERE userId=?').run(Number(req.params.id));db.prepare('DELETE FROM users WHERE id=?').run(Number(req.params.id));audit(req,'Deleted user',req.params.id);res.json({ok:true});}catch(e){next(e);}});
app.get('/api/backup',permit('admin','export'),(req,res)=>{audit(req,'Exported backup','Business data');res.attachment('tradeflow-backup.json').json({version:1,products:rows(db,'products'),customers:rows(db,'customers'),vendors:rows(db,'vendors'),documents:rows(db,'documents'),movements:db.prepare('SELECT * FROM movements').all(),settings:JSON.parse(db.prepare('SELECT data FROM settings').get().data)});});
app.post('/api/restore',permit('admin','edit'),(req,res,next)=>{try{const b=req.body;if(b.version!==1||!['products','customers','vendors','documents','movements'].every(k=>Array.isArray(b[k]))||!b.settings?.company)throw Error('Invalid backup file');db.exec('BEGIN IMMEDIATE');for(const t of ['movements','documents','products','customers','vendors'])db.exec(`DELETE FROM ${t}`);for(const t of ['products','customers','vendors'])for(const r of b[t])db.prepare(`INSERT INTO ${t}(id,data) VALUES(?,?)`).run(r.id,JSON.stringify(r));for(const d of b.documents)db.prepare('INSERT INTO documents(id,kind,date,data) VALUES(?,?,?,?)').run(d.id,d.kind,d.date,JSON.stringify(d));for(const m of b.movements)db.prepare('INSERT INTO movements VALUES(?,?,?,?,?)').run(m.id,m.productId,m.date,m.quantity,m.reason);put(db,'settings',b.settings,1);db.exec('COMMIT');audit(req,'Restored backup','Business data replaced');res.json({ok:true});}catch(e){try{db.exec('ROLLBACK');}catch{}next(e);}});
app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint not found'}));app.use((err,req,res,next)=>res.status(400).json({error:err.message.includes('UNIQUE')?'This email or identifier already exists':err.message}));
let viteServer;
if(process.env.NODE_ENV==='production'){app.use(express.static('dist'));app.get('/{*path}',(req,res)=>res.sendFile(process.cwd()+'/dist/index.html'));}else{const {createServer}=await import('vite');viteServer=await createServer({server:{middlewareMode:true,allowedHosts:configuredOrigins.map(origin=>new URL(origin).hostname),hmr:{server:httpServer,...(process.env.CODESPACES==='true'?{clientPort:443}:{})}},appType:'spa'});app.use(viteServer.middlewares);}
const port=Number(process.env.PORT||3000);
httpServer.on('error',error=>{
 console.error(error.code==='EADDRINUSE'?`Port ${port} is already in use. Stop the older Tradeflow server before restarting.`:`Server startup failed: ${error.message}`);
 process.exit(1);
});
httpServer.listen(port,'0.0.0.0',error=>{
 if(error)return; // Node may pass a bind error to the callback; the error handler reports it.
 console.log('Tradeflow running on port '+port);
 console.log('Public origins: '+(configuredOrigins.join(', ')||'local address only; set APP_ORIGIN for an HTTPS proxy'));
});
let shuttingDown=false;
async function shutdown(){
 if(shuttingDown)return;shuttingDown=true;
 const timeout=setTimeout(()=>process.exit(0),5000);timeout.unref();
 await viteServer?.close();
 httpServer.close(()=>{db.close();process.exit(0);});
 httpServer.closeAllConnections();
}
process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
