import test from 'node:test';import assert from 'node:assert/strict';import{openDB,put,rows,createDocument,hashPassword,verifyPassword}from'../db.js';
async function fixture(){const db=openDB(':memory:');await put(db,'products',{name:'Widget',sku:'W1',stock:10,purchasePrice:5,sellingPrice:10});await put(db,'customers',{name:'Buyer',balance:0});await put(db,'vendors',{name:'Supplier',balance:0});return db;}
test('purchase updates stock and payable; vendor payment settles invoice',async()=>{const db=await fixture();await createDocument(db,'purchases',{partyId:1,items:[{productId:1,quantity:5,rate:5}],paid:10,tax:0});assert.equal((await rows(db,'products'))[0].stock,15);assert.equal((await rows(db,'vendors'))[0].balance,15);await createDocument(db,'payments',{direction:'paid',partyId:1,amount:15});assert.equal((await rows(db,'vendors'))[0].balance,0);assert.equal((await rows(db,'documents')).find(d=>d.kind==='purchases').status,'Paid');db.close();});
test('sale calculations and payment maintain customer ledger',async()=>{const db=await fixture();const sale=await createDocument(db,'sales',{partyId:1,items:[{productId:1,quantity:3,rate:10}],discount:2,tax:10,charges:1,paid:5});assert.equal(sale.total,31.8);assert.equal((await rows(db,'products'))[0].stock,7);assert.equal((await rows(db,'customers'))[0].balance,26.8);await createDocument(db,'payments',{direction:'received',partyId:1,amount:26.8});assert.equal((await rows(db,'customers'))[0].balance,0);assert.equal((await rows(db,'documents')).find(d=>d.kind==='sales').outstanding,0);db.close();});
test('failed multi-line invoice rolls back all inventory and balances',async()=>{const db=await fixture();await assert.rejects(async()=>await createDocument(db,'sales',{partyId:1,items:[{productId:1,quantity:2,rate:10},{productId:1,quantity:20,rate:10}]}),/Insufficient/);assert.equal((await rows(db,'products'))[0].stock,10);assert.equal((await rows(db,'customers'))[0].balance,0);assert.equal((await rows(db,'documents')).length,0);assert.equal(db.prepare('SELECT count(*) n FROM movements').get().n,0);db.close();});
test('invalid financial inputs and overpayments are rejected',async()=>{const db=await fixture();for(const amount of [-1,'bad',0])await assert.rejects(async()=>await createDocument(db,'expenses',{amount}));await assert.rejects(async()=>await createDocument(db,'sales',{partyId:1,items:[{productId:1,quantity:1,rate:10}],paid:11}),/exceeds/);await assert.rejects(async()=>await createDocument(db,'payments',{direction:'received',partyId:1,amount:1}),/exceeds/);assert.equal((await rows(db,'products'))[0].stock,10);db.close();});
test('damaged stock adjustments cannot create negative stock',async()=>{const db=await fixture();await createDocument(db,'adjustments',{productId:1,direction:'out',amount:2,reason:'Damaged stock'});assert.equal((await rows(db,'products'))[0].stock,8);await assert.rejects(async()=>await createDocument(db,'adjustments',{productId:1,direction:'out',amount:9}));db.close();});
test('passwords use salted hashes and verify correctly',async()=>{const hash=hashPassword('test-password');assert.ok(verifyPassword('test-password',hash));assert.equal(verifyPassword('wrong',hash),false);assert.notEqual(hash,hashPassword('test-password'));});
test('purchase cost uses weighted average and sale snapshots cost excluding tax',async()=>{const db=await fixture();await createDocument(db,'purchases',{partyId:1,items:[{productId:1,quantity:5,rate:10}]});assert.equal((await rows(db,'products'))[0].purchasePrice,6.67);const sale=await createDocument(db,'sales',{partyId:1,items:[{productId:1,quantity:2,rate:10}],discount:2,tax:10});assert.equal(sale.cost,13.34);assert.equal(sale.revenue,18);assert.equal(sale.total,19.8);db.close();});
test('invalid calendar dates and transaction directions fail without changes',async()=>{const db=await fixture();await assert.rejects(async()=>await createDocument(db,'expenses',{date:'2026-02-31',amount:1}),/date/);await assert.rejects(async()=>await createDocument(db,'payments',{direction:'invalid',partyId:1,amount:1}),/direction/);assert.equal((await rows(db,'documents')).length,0);db.close();});
